### ISSUE TITLE
Problem with the NYU dataset Matlab code

### ISSUE THREAD

**Issue by Scienceseb** [simonmeister/pytorch-mono-depth#2]
Hi I just want to know if you make any modification for the file process_raw.m or other file in the official Toolbox for the NYU dataset. Im getting an error about the get_synched_framed, its seem that it cannot go through the scene subfile (like basement_0001a), its return 0 file in the scene but all the files are there. I did it on Octave in Linux Mint and I used the Raw dataset, Single File (~428 GB) from https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html.

Thanks a lot for your help.

**Comment by simonmeister** [comment]
Hmm I guess using octave might be an issue. It would be worth trying it with Matlab I think.

**Comment by jaspereb** [comment]
I had the same issue in matlab, attached is an updated version of the matlab file that goes through subdirectories (change the extension to .m)
[process_raw.txt](https://github.com/simonmeister/pytorch-mono-depth/files/2787200/process_raw.txt)

**Comment by abdur4373** [comment]
Hello everyone, I am using the same toolbox, It is doing well on raw dataset I downloaded from NYU [page](https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html) however I want to process my own kinect data and make my own depth dataset for training of neural network.
I wanted to know before giving it to project_depth_map.m function they are using swapbytes.m function of matlab.

First question is why would they use that function 
Secondly there is this condition of
`  imgDepth(imgDepth < 600) = 2047; 
  imgDepth(noiseMask) = 2047;`

Why are they taking these values because my data is in mm and max value of like 4000  which makes it 4 meters.

I am really stuck in this issue could you help me please,
I would appreciate that.
Regards
